import PDFDocument from "pdfkit";

interface TreatmentPlanData {
  patientName: string;
  caseId: number;
  cancerType: string;
  stage?: string;
  tumorSize?: string;
  treatmentPlan: {
    summary: string;
    primaryRecommendation: string;
    alternativeOptions: string[];
    considerations: string[];
    followUp: string[];
    references: string[];
  };
  generatedAt: Date;
  doctorName?: string;
}

export function generateTreatmentPlanPDF(data: TreatmentPlanData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", reject);

      doc
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("DoctorPath AI", { align: "center" })
        .fontSize(16)
        .text("Oncology Treatment Plan Report", { align: "center" })
        .moveDown();

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Generated: ${data.generatedAt.toLocaleDateString()}`, { align: "right" })
        .text(`Case ID: ${data.caseId}`, { align: "right" })
        .moveDown();

      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown();

      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text("Patient Information")
        .moveDown(0.5);

      doc
        .fontSize(11)
        .font("Helvetica")
        .text(`Patient: ${data.patientName}`)
        .text(`Cancer Type: ${data.cancerType}`)
        .text(`Stage: ${data.stage || "Not specified"}`)
        .text(`Tumor Size: ${data.tumorSize || "Not specified"}`);

      if (data.doctorName) {
        doc.text(`Attending Physician: ${data.doctorName}`);
      }
      doc.moveDown();

      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text("Clinical Summary")
        .moveDown(0.5);

      doc
        .fontSize(11)
        .font("Helvetica")
        .text(data.treatmentPlan.summary, { align: "justify" })
        .moveDown();

      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text("Primary Recommendation")
        .moveDown(0.5);

      doc
        .fontSize(11)
        .font("Helvetica")
        .text(data.treatmentPlan.primaryRecommendation, { align: "justify" })
        .moveDown();

      if (data.treatmentPlan.alternativeOptions.length > 0) {
        doc
          .fontSize(14)
          .font("Helvetica-Bold")
          .text("Alternative Treatment Options")
          .moveDown(0.5);

        data.treatmentPlan.alternativeOptions.forEach((option, index) => {
          doc.fontSize(11).font("Helvetica").text(`${index + 1}. ${option}`);
        });
        doc.moveDown();
      }

      if (data.treatmentPlan.considerations.length > 0) {
        doc
          .fontSize(14)
          .font("Helvetica-Bold")
          .text("Important Considerations")
          .moveDown(0.5);

        data.treatmentPlan.considerations.forEach((consideration) => {
          doc.fontSize(11).font("Helvetica").text(`- ${consideration}`);
        });
        doc.moveDown();
      }

      if (data.treatmentPlan.followUp.length > 0) {
        doc
          .fontSize(14)
          .font("Helvetica-Bold")
          .text("Follow-Up Recommendations")
          .moveDown(0.5);

        data.treatmentPlan.followUp.forEach((item) => {
          doc.fontSize(11).font("Helvetica").text(`- ${item}`);
        });
        doc.moveDown();
      }

      doc.moveDown();
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown();

      doc
        .fontSize(9)
        .font("Helvetica-Oblique")
        .fillColor("gray")
        .text(
          "DISCLAIMER: This treatment plan is generated by an AI decision support system and is intended for informational purposes only. " +
          "It should not be considered as a substitute for professional medical advice, diagnosis, or treatment. " +
          "Always consult with a qualified healthcare provider for medical decisions.",
          { align: "justify" }
        )
        .moveDown();

      if (data.treatmentPlan.references.length > 0) {
        doc
          .fontSize(10)
          .font("Helvetica-Bold")
          .fillColor("black")
          .text("References")
          .moveDown(0.5);

        data.treatmentPlan.references.forEach((ref) => {
          doc.fontSize(9).font("Helvetica").text(`- ${ref}`);
        });
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
